Repository Team-Sthub/Sthub, pull requests merged in 2024-04, with the labels that each got.

#8 Feat/4
  src/main/java/com/ssd/sthub/domain/GComment.java
  src/main/java/com/ssd/sthub/domain/GroupBuying.java
  src/main/java/com/ssd/sthub/domain/Member.java
  src/main/java/com/ssd/sthub/domain/Participation.java
Labels: ✨ feature

#9 feat(#3) 중고거래-member 매핑
  src/main/java/com/ssd/sthub/domain/Purchase.java
  src/main/java/com/ssd/sthub/domain/SComment.java
  src/main/java/com/ssd/sthub/domain/SecondHand.java
Labels: ✨ feature

#19 feat(#12) 공동구매 댓글, 신청 Repository
  src/main/java/com/ssd/sthub/repository/GCommentRepository.java
  src/main/java/com/ssd/sthub/repository/ParticipationRepository.java
Labels: ✨ feature

#23 Feat/14
  src/main/java/com/ssd/sthub/domain/Member.java
  src/main/java/com/ssd/sthub/domain/Purchase.java
  src/main/java/com/ssd/sthub/domain/SComment.java
  src/main/java/com/ssd/sthub/domain/Secondhand.java
  src/main/java/com/ssd/sthub/exception/ApplicationException.java
  src/main/java/com/ssd/sthub/exception/BadRequestException.java
  src/main/java/com/ssd/sthub/exception/ExceptionAdvice.java
  src/main/java/com/ssd/sthub/exception/InternalServerErrorException.java
  src/main/java/com/ssd/sthub/exception/response/BaseResponse.java
  src/main/java/com/ssd/sthub/exception/response/ErrorCode.java
  src/main/java/com/ssd/sthub/exception/response/ErrorResponse.java
  src/main/java/com/ssd/sthub/exception/response/SuccessResponse.java
  src/main/java/com/ssd/sthub/repository/PurchaseRepository.java
  src/main/java/com/ssd/sthub/repository/SCommentRepository.java
  src/main/java/com/ssd/sthub/repository/SecondhandRepository.java
  src/main/java/com/ssd/sthub/service/PurchaseQueryService.java
  src/main/java/com/ssd/sthub/service/PurchaseService.java
  src/main/java/com/ssd/sthub/service/SCommentQueryService.java
  src/main/java/com/ssd/sthub/service/SCommentService.java
  src/main/java/com/ssd/sthub/service/SecondhandQueryService.java
  src/main/java/com/ssd/sthub/service/SecondhandService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ feature

#24 feat(#20) 공동구매 댓글, 신청 Service & Participation accept 변경
  src/main/java/com/ssd/sthub/domain/Participation.java
  src/main/java/com/ssd/sthub/repository/GCommentRepository.java
  src/main/java/com/ssd/sthub/repository/ParticipationRepository.java
  src/main/java/com/ssd/sthub/service/GCommentQueryService.java
  src/main/java/com/ssd/sthub/service/GCommentService.java
  src/main/java/com/ssd/sthub/service/ParticipationQueryService.java
  src/main/java/com/ssd/sthub/service/ParticipationService.java
Labels: ⚡️fix, ✨ feature

#27 fix : response 패키지 구조 수정
  src/main/java/com/ssd/sthub/exception/response/BaseResponse.java
  src/main/java/com/ssd/sthub/response/ErrorCode.java
  src/main/java/com/ssd/sthub/response/ErrorResponse.java
  src/main/java/com/ssd/sthub/response/SuccessResponse.java
  src/main/java/com/ssd/sthub/response/exception/ApplicationException.java
  src/main/java/com/ssd/sthub/response/exception/ExceptionAdvice.java
  src/main/java/com/ssd/sthub/response/exception/InternalServerErrorException.java
Labels: ⚡️fix

#32 feat(#25) : 중고거래, 댓글, 구매 controller + dto 작성
  src/main/java/com/ssd/sthub/controller/SecondhandController.java
  src/main/java/com/ssd/sthub/domain/Purchase.java
  src/main/java/com/ssd/sthub/domain/SComment.java
  src/main/java/com/ssd/sthub/domain/Secondhand.java
  src/main/java/com/ssd/sthub/dto/secondhand/SCommentDTO.java
  src/main/java/com/ssd/sthub/dto/secondhand/SecondhandDTO.java
  src/main/java/com/ssd/sthub/repository/SCommentRepository.java
  src/main/java/com/ssd/sthub/service/PurchaseService.java
  src/main/java/com/ssd/sthub/service/SCommentQueryService.java
  src/main/java/com/ssd/sthub/service/SCommentService.java
  src/main/java/com/ssd/sthub/service/SecondhandQueryService.java
  src/main/java/com/ssd/sthub/service/SecondhandService.java
Labels: ✨ feature

#34 feat(#28) : 공동구매 댓글, 신청 관련 service, controller
  src/main/java/com/ssd/sthub/controller/GCommentController.java
  src/main/java/com/ssd/sthub/controller/ParticipationController.java
  src/main/java/com/ssd/sthub/domain/GComment.java
  src/main/java/com/ssd/sthub/domain/Participation.java
  src/main/java/com/ssd/sthub/dto/gComment/GCommentRequestDto.java
  src/main/java/com/ssd/sthub/dto/gComment/GCommentResponseDto.java
  src/main/java/com/ssd/sthub/dto/participation/ParticipationRequestDto.java
  src/main/java/com/ssd/sthub/dto/participation/ParticipationResponseDto.java
  src/main/java/com/ssd/sthub/repository/GCommentRepository.java
  src/main/java/com/ssd/sthub/repository/ParticipationRepository.java
  src/main/java/com/ssd/sthub/service/GCommentQueryService.java
  src/main/java/com/ssd/sthub/service/GCommentService.java
  src/main/java/com/ssd/sthub/service/ParticipationQueryService.java
  src/main/java/com/ssd/sthub/service/ParticipationService.java
Labels: ⚡️fix, ✨ feature

#36 feat(#25) : 중고거래, 댓글, 구매 기능 구현
  src/main/java/com/ssd/sthub/controller/PurchaseController.java
  src/main/java/com/ssd/sthub/controller/SecondhandController.java
  src/main/java/com/ssd/sthub/repository/PurchaseRepository.java
  src/main/java/com/ssd/sthub/service/PurchaseQueryService.java
  src/main/java/com/ssd/sthub/service/SecondhandQueryService.java
Labels: ✨ feature
